# Generated by Django 4.1 on 2022-08-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibasics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='data',
            new_name='date',
        ),
    ]
